In [1]:
#numpy library idea
#install numpy function in python
import numpy as np
mylist=[1,2,3,4]
type(np.array(mylist))
arr=np.array(mylist)
arr

array([1, 2, 3, 4])

In [3]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.zeros(5)
#generate floating point array matrix


array([0., 0., 0., 0., 0.])

In [5]:
np.zeros((3,5))
#matrix of zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.ones((3,5)) 
#it works for one as well..everything is floating point values

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
#all operations in numpy as in the forms of array
np.random.randint(0,10) #for random no. generation

5

In [17]:
#generate array of random no.
np.random.randint(0,1000,(4,4))

array([[477, 729, 615, 150],
       [449, 522, 503, 610],
       [412, 787, 716, 249],
       [154,  53, 518, 735]])

In [29]:
np.random.seed(101)
arr=np.random.randint(0,100,10) # generate not changable random sample
arr.max() #for knowing maximum
arr.min() #for knowing minimum
arr.mean() #for average
arr.argmax() #maximum no. index value
arr.argmin() #minimum no. index value
arr.reshape(5,2) #to reshape the array in matrix format

array([[95, 11],
       [81, 70],
       [63, 87],
       [75,  9],
       [77, 40]])

In [37]:
mat= np.arange(0,100).reshape(10,10) #10*10 matrix format

mat


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [50]:
mat[1,1]
mat[0,:]
mat[:,0]
mat[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])